services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9000:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - booking_network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    networks:
      - booking_network

networks:
  booking_network:
    external: true
